services:
  app:
    build:
      context: .
      target: development
    container_name: nestjs-task-management-app
    ports:
      - '${APP_HOST_PORT:-3000}:3000'
    environment:
      PORT: 3000
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      DB_DATABASE: task-management
    volumes:
      - .:/usr/src/app
      - app_node_modules:/usr/src/app/node_modules
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:16-alpine
    container_name: nestjs-task-management-postgres
    ports:
      - '${POSTGRES_HOST_PORT:-5434}:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: task-management
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres -d task-management']
      interval: 5s
      timeout: 5s
      retries: 10

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: nestjs-task-management-pgadmin
    ports:
      - '${PGADMIN_HOST_PORT:-5050}:80'
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  app_node_modules:
  postgres_data:
  pgadmin_data:
